class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror2'
        self.UnzipMirrorCommand = 'unzipmirror2'
        self.TarMirrorCommand = 'tarmirror2'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'list'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize2'
        self.UnAuthorizeCommand = 'unauthorize2'
        self.AddSudoCommand = 'addsudo2'
        self.RmSudoCommand = 'rmsudo2'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch1'
        self.TarWatchCommand = 'tarwatch2'
        self.DeleteCommand = 'del'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
